### ISSUE TITLE
giving blank page for flutter web

### ISSUE THREAD

**Issue by gauravmehta13** [lejard-h/google_maps_webservice#100]

**Comment by gauravmehta13** [comment]
PS i dont have firebase requirement in my project only using maps
![image](https://user-images.githubusercontent.com/51997260/111875601-ac289900-89c0-11eb-865d-cc974c517695.png)

**Comment by lejard-h** [comment]
Can't understand the issue here .

What are you trying to do ? 
Which version are you using ? 
What is producing blank page ?

Firebase is not part of this package.
