### ISSUE TITLE
Unhandled Exception: Unhandled error type 'Null' is not a subtype of type 'String' calling getDetailsByPlaceId

### ISSUE THREAD

**Issue by dagix5** [lejard-h/google_maps_webservice#103]
Calling `getDetailsByPlaceId` it throws this:
`E/flutter ( 7283): #0      _$PlaceDetailsFromJson (package:google_maps_webservice/src/places.g.dart:136:37)`
`E/flutter ( 7283): #1      new PlaceDetails.fromJson (package:google_maps_webservice/src/places.dart:710:7)`
`E/flutter ( 7283): #2      _$PlacesDetailsResponseFromJson (package:google_maps_webservice/src/places.g.dart:294:26)`
`E/flutter ( 7283): #3      new PlacesDetailsResponse.fromJson (package:google_maps_webservice/src/places.dart:838:7)`
`E/flutter ( 7283): #4      GoogleMapsPlaces._decodeDetailsResponse (package:google_maps_webservice/src/places.dart:528:29)`
`E/flutter ( 7283): #5      GoogleMapsPlaces.getDetailsByPlaceId (package:google_maps_webservice/src/places.dart:126:12)`

It seems that `adr_address` could be null.

version: `0.0.20-nullsafety.2`

**Comment by lejard-h** [comment]
I just published a new version.

Let me know if you have any other issue

**Comment by dagix5** [comment]
Hi, thanks for the new version but the same error occurs for `utc_offset`.

**Comment by erf** [comment]
I experienced the same now when calling `GoogleMapsPlaces.searchByText`. It fails in the following:

```

PlacesSearchResult _$PlacesSearchResultFromJson(Map<String, dynamic> json) {
  return PlacesSearchResult(
    id: json['id'] as String,
```

there is no `id` field in `json`.

I'm on version: `^0.0.20-nullsafety.3`

**Comment by erf** [comment]
Maybe `PlacesSearchResult.id` should be made optional..?

**Comment by mbilalakmal** [comment]
> Hi, thanks for the new version but the same error occurs for `utc_offset`.
> I edited `places.dart` manually in my project making nullable this field and it works for me.
> I don't know if there are other similar problems.

I can confirm that this is present in the latest null-safe version: 0.0.20-nullsafety.4
