### ISSUE TITLE
Get Street, address, city, state from Prediction object.

### ISSUE THREAD

**Issue by ask007learning** [lejard-h/google_maps_webservice#11]
How to get street, address, city, state from Prediction object.  There is a 'terms' list field that have the information but how to know where in the list that information is present.

For reference, in one of my javascript app, I am using google autocomplete and to get specific information I did the following:

```
let place:Place = new Place();
    googlePlace.address_components.forEach(a =>{
      if(a.types.indexOf("street_number") > -1){
        place.streetNumber = a.long_name;
      }else if(a.types.indexOf("route") > -1){
        place.address = a.long_name;
      }else if(a.types.indexOf("locality") > -1){
        place.city = a.long_name;
      }else if(a.types.indexOf("administrative_area_level_1") > -1){
        place.state = a.short_name;
      }else if(a.types.indexOf("postal_code") > -1){
        place.zip = a.short_name;
      } else if(a.types.indexOf("country") > -1){
        place.country = a.short_name;
      }
    });
```

**Comment by lejard-h** [comment]
to get details about the prediction, you need to pass the place_id to the `getDetails()` function

https://pub.dartlang.org/documentation/google_maps_webservice/latest/google_maps_webservice.places/GoogleMapsPlaces/getDetailsByPlaceId.html

then you will received address_components
