### ISSUE TITLE
Unhandled Exception: FormatException: Unexpected character (at character 1)  <!DOCTYPE HTML PUBLIC '-//IETF//DTD HTML 2.0//EN'>

### ISSUE THREAD

**Issue by Muniru0** [lejard-h/google_maps_webservice#112]
E/flutter (14123):
E/flutter (14123): 
E/flutter (14123): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
E/flutter (14123): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1271:9)
E/flutter (14123): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:936:22)
E/flutter (14123): #3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
E/flutter (14123): #4      JsonDecoder.convert (dart:convert/json.dart:505:36)
E/flutter (14123): #5      JsonCodec.decode (dart:convert/json.dart:156:41)
E/flutter (14123): #6      GoogleMapsPlaces._decodeDetailsResponse (package:google_maps_webservice/src/places.dart:386:43)
E/flutter (14123): #7      GoogleMapsPlaces.getDetailsByPlaceId (package:google_maps_webservice/src/places.dart:124:12)
E/flutter (14123): <asynchronous suspension>
E/flutter (14123): #8      _CourierLiveLocationRouteState.showLocationMakersWithPolyline (package:Customer4pay/ui/routes/parcels/courier_live_location_route.dart:170:63)
E/flutter (14123): <asynchronous suspension>
E/flutter (14123): #9      _CourierLiveLocationRouteState._onMapCreated (package:Customer4pay/ui/routes/parcels/courier_live_location_route.dart:236:6)
E/flutter (14123): <asynchronous suspension>
E/flutter (14123): #10     _GoogleMapState.onPlatformViewCreated (package:google_maps_flutter/src/google_map.dart:324:26)
E/flutter (14123): <asynchronous suspension>
E/flutter (14123): #11     AndroidViewController.create (package:flutter/src/services/platform_views.dart:753:15)
E/flutter (14123): <asynchronous suspension>
E/flutter (14123): #12     TextureAndroidViewController.create (package:flutter/src/services/platform_views.dart:1018:34)
E/flutter (14123): #13     TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1002:14)
E/flutter (14123): #14     RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (14123): #15     RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (14123): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1756:9)
E/flutter (14123): #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (14123): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (14123): #19     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:268:14)
E/flutter (14123): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (14123): #21     RenderStack.layoutPositionedChild (package:flutter/src/rendering/stack.dart:491:11)
E/flutter (14123): #22     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:587:30)
E/flutter (14123): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (14123): #24     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:268:14)
E/flutter (14123): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (14123): #26     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:268:14)
E/flutter (14123): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (14123): #28     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:560:15)
E/flutter (14123): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (14123): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (14123): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (14123): #32     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
E/flutter (14123): #33     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:498:7)
E/flutter (14123): #34     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
E/flutter (14123): #35     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:402:14)
E/flutter (14123): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (14123): #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (14123): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (14123): #39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (14123): #40     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1308:11)
W/le.Customer4pa(14123): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)

I am trying to use a proxy server instead of the api key in my application, but to no avail. this is what I get when I try to use the base url parameter. this is my base url www.some.6til.me(this is the format of the url). thanks in advance

**Comment by lejard-h** [comment]
The lib is not receiving JSON but HTML instead and can't parse it.

This is clearly something related to your proxy (return 404 not found page?, or any other error ?).

Sorry I can't help you

**Comment by SivaFullStackDeveloper** [comment]
FormatException (FormatException: Unexpected character (at character 1)
<!DOCTYPE html>
^
)

**Comment by SivaFullStackDeveloper** [comment]
iam gettin g the same erroe please hellp
