### ISSUE TITLE
'Int' is not double

### ISSUE THREAD

**Issue by Timouri** [lejard-h/google_maps_webservice#15]
Please, add a checking in the file 'core.dart' line 9. If json handed over integer, exception is thrown
`factory Location.fromJson(Map json) =>
      json != null ? new Location(json["lat"], json["lng"]) : null;`
Maybe, like here?
```  
factory Location.fromJson(Map json) => json != null
      ? new Location(
          json["lat"].runtimeType == double
              ? json["lat"]
              : (json["lat"] as int).toDouble(),
          json["lng"])
      : null;
```

**Comment by lejard-h** [comment]
fixed ins `0.0.8`
