### ISSUE TITLE
unable to import

### ISSUE THREAD

**Issue by dss539** [lejard-h/google_maps_webservice#2]
It seems that I am unable to import from this package.
![image](https://user-images.githubusercontent.com/6412918/36959560-bd08355e-2010-11e8-8b3c-fef8b3a6de5e.png)

my pubspec includes the correct line, I think...
```
  location: ^1.1.7
  google_maps_webservice: ^0.0.3
```

I have no trouble using , e.g., the location package.
Is this a problem with the package, or a problem in my configuration and usage?

**Comment by lejard-h** [comment]
Hello,

You missed the semi-column at the end of the import.
If you still have the error, I suggest you to do a `pub upgrade`

And if it works, you should report the issue on the dart SDK, the import should not fail like that if no `;`

**Comment by dss539** [comment]
Thanks for the tip. Unfortunately, I still have the other error.
![image](https://user-images.githubusercontent.com/6412918/36976599-328086de-204c-11e8-83f3-2be491758838.png)

I think the semi-colon was a red herring.

When I have time, I will make a public repo that, I hope, illustrates the issue.

**Comment by lejard-h** [comment]
is it possible to share your pubspec.yaml here ?

you can also try to remove `.pub`, `.packages`, `pubspeck.lock`

**Comment by dss539** [comment]
Sorry for the delayed response, and thanks for the help.
I created a new flutter project in Android studio to reproduce the issue... and it worked fine.
After comparing the two project, I found absolutely nothing different in regards to this library.
So I tried a few things, such as removing and re-adding entries in the pubspec.yaml, rebuilding the package cache, and re-starting Android studio.
Finally, something worked.

I am certain there is nothing wrong with this package. There may have been something wrong with Android Studio, or it may have been user error, though I have a hard time figuring out what I may have done wrong.

In any case, I no longer have the error. Thanks for your help, and sorry to waste your time.

**Comment by shubh420** [comment]
Same thing happened with me. I do never get these kind of errors when adding a package in my pubspec file. but for this package I was successfully able to add the package in pubspec file but I was not able to import the files from the package.

Its only when I invalidate and restart the android studio, things started working.
