### ISSUE TITLE
Why has been removed session token management?

### ISSUE THREAD

**Issue by anlarosa** [lejard-h/google_maps_webservice#20]
Why "Merge pull request #19 from prolutionsGmbH/configurable_base_url" has removed session token management?

**Comment by sdolski** [comment]
@lejard-h PR #18 and PR #19 were developed based on the current master branch. I did not know if both PRs will be accepted, so they were created independently. It seems like the merge from PR #19 did override the session token functionality.

**Comment by anlarosa** [comment]
Hello guys...any news? Do you plan to ripristinate the "session token management" feature? Thank you.

**Comment by sdolski** [comment]
@anlarosa no time today but I will provide a new pull request till the end of the week

**Comment by anlarosa** [comment]
Looks like has been implemented this feature. Can you please merge the pull request into the master?

**Comment by lejard-h** [comment]
fix in `0.0.11`
