### ISSUE TITLE
How I can consume Google map web services API in my flutter APP

### ISSUE THREAD

**Issue by 1abid** [lejard-h/google_maps_webservice#28]
I am new in Flutter, and I have pretty good knowledge of using Google maps APIs for native Android Apps. However, in my flutter app I need Google Places search Auto-complete. I came across to this plugin 
it consumes google maps APIs such as directions, places and geocoding using Google web services. My question is having low understanding and experiences in setting up web services for google maps API, how I can use plugin in my flutter app? For example, if I had to use places API in android I would have enabled Goole Places SDK in cloud console and generate an API restricting for Android App. But for flutter both Android and iOS is going to use same services from web API call. what should I do? And right now I have no backend knowledge to set up a domain to use while creating the API from console.

**Comment by 1abid** [comment]
# # # #

**Comment by 1abid** [comment]
#

**Comment by 1abid** [comment]
#

**Comment by msaliminia** [comment]
+1

**Comment by msaliminia** [comment]
@1abid did you find the answer?

**Comment by 1abid** [comment]
> @1abid did you find the answer?
Yes, I did, I created an API key in google console and didn't restrict it.

**Comment by zeshuaro** [comment]
There is a solution to this issue now, please see https://github.com/lejard-h/google_maps_webservice/issues/85#issuecomment-752829368 for my comment.
