### ISSUE TITLE
NoSuchMethodError: The getter 'geometry' was called on null.

### ISSUE THREAD

**Issue by 1abid** [lejard-h/google_maps_webservice#30]
Currently, I using this package in my app and before implementing it I tried using the example app. But in the overlay mode when I click on a prediction this error is being shown.
<img width="1835" alt="screenshot 2019-02-13 at 12 58 58 pm" src="https://user-images.githubusercontent.com/6067801/52692948-8a61ba00-2f8f-11e9-8b1f-0cdc313e319c.png">

**Comment by MayurPrajapati** [comment]
I got same issue..
Is it's been solved?
Please share the solution.

**Comment by 1abid** [comment]
> I got same issue..
> Is it's been solved?
> Please share the solution.

@MayurPrajapati  I faced the issue, but it is nothing related to this plugin.
The reason I faced the issue was calling httpClient.dispose() before waiting for the function which is returning a Future.
