### ISSUE TITLE
token

### ISSUE THREAD

**Issue by momoDragon** [lejard-h/google_maps_webservice#31]
library google_maps_webservice.places.autocomplete.example;

import 'dart:io';
import 'package:google_maps_webservice/places.dart';

final places = new GoogleMapsPlaces(apiKey: Platform.environment["API_KEY"]);

main() async {
  String sessionToken = "xyzabc_1234";
  PlacesAutocompleteResponse res =
      await places.autocomplete("Amoeba", sessionToken: sessionToken);

  if (res.isOkay) {
    // list autocomplete prediction
    res.predictions.forEach((Prediction p) {
      print("- ${p.description}");
    });

    // get detail of the first result
    PlacesDetailsResponse details = await places.getDetailsByPlaceId(
        res.predictions.first.placeId,
        sessionToken: sessionToken);

    print("\nDetails :");
    print(details.result.formattedAddress);
    print(details.result.formattedPhoneNumber);
    print(details.result.url);
  } else {
    print(res.errorMessage);
  }

  places.dispose();
}

Issue: 
I ran this code which i found in the example and i got an error.

error: 
You must use an API key to authenticate each request to Google Maps Platform APIs.

what i tried: 
my api key has worked on 
final places = new GoogleMapsPlaces(apiKey: "API_KEY");
but when i used final 
places = new GoogleMapsPlaces(apiKey: Platform.environment["API_KEY"]);
it gave me that error.

**Comment by domesticmouse** [comment]
What happens if you assign `Platform.environment["API_KEY"]` to a local variable, and print out said variable?

**Comment by lejard-h** [comment]
What platform are you using ?

`Platform.environment["API_KEY"]` works only on server-side doing `export API_KEY="YOUR_KEY"` before launching your app

if you are on flutter it won't work, you need to use a constant value somewhere in your code that you can set using [flavours](https://flutter.dev/docs/deployment/flavors).

On browser app you can use an env variable at build time in your build.yaml
```
    builders:
      build_web_compilers|entrypoint:
        release_options:
          dart2js_args:
          - -DAPI_KEY=YOUR_API_KEY
```
and use it like this `const apiKey = const String.fromEnvironment('API_KEY', defaultValue: 'default_key');
