### ISSUE TITLE
Returning only 1 result

### ISSUE THREAD

**Issue by shinayser** [lejard-h/google_maps_webservice#35]
All requests I do by text returns me only one result. Is it a intentional behavior or there is something worng with the api?

I am am currently on this version: ` google_maps_webservice: ^0.0.12`

My code:
![image](https://user-images.githubusercontent.com/1146982/54774736-26b05980-4beb-11e9-9a2d-9a8c90ecf0de.png)

Prints:
![image](https://user-images.githubusercontent.com/1146982/54774754-36c83900-4beb-11e9-8efc-498241f68226.png)

**Comment by shinayser** [comment]
I've set the "location" parameter and seems now it is retuning more results. Not this lib problem. You may close this issue.

**Comment by juanjoserodrigolazaro** [comment]
> I've set the "location" parameter and seems now it is retuning more results. Not this lib problem. You may close this issue.

how did you make it?

**Comment by shinayser** [comment]
> > I've set the "location" parameter and seems now it is retuning more results. Not this lib problem. You may close this issue.
> 
> how did you make it?

It didin't fixed 100% but gave me more results on some requests.

![image](https://user-images.githubusercontent.com/1146982/55037620-1b9b6600-4ffd-11e9-88ee-9ea099a0bbc9.png)
