### ISSUE TITLE
is it support to both android and ios ?

### ISSUE THREAD

**Issue by minh98** [lejard-h/google_maps_webservice#36]
is it support to both android and ios ?

**Comment by minh98** [comment]
MapView.setApiKey("google_map_key");
which api key to add ?
android api key or ios ?

**Comment by FarshanAhamed** [comment]
Did you find a way to provide both keys?

**Comment by lejard-h** [comment]
Sorry for that, I just updated the README

You need a Web API key. [Here](https://developers.google.com/places/web-service/get-api-key)
And Android or iOS API key won't work.
