### ISSUE TITLE
 distance response REQUEST_DENIED

### ISSUE THREAD

**Issue by temirfe** [lejard-h/google_maps_webservice#37]
I am using right api_key as shown in the example:  `final GoogleDistanceMatrix distanceMatrix = GoogleDistanceMatrix(  apiKey: Platform.environment["my_api"]);` but getting error request denied

**Comment by lejard-h** [comment]
Did you enable billing on your api key ?
https://developers.google.com/maps/documentation/distance-matrix/get-api-key

```
Reminder: To use the Distance Matrix API, you must get an API key and you must enable billing. You can enable billing when you get your API key (see the Quick guide) or as a separate process (see Usage and Billing).
```

And check if it is enable on your console https://console.cloud.google.com
