### ISSUE TITLE
related to place picker?

### ISSUE THREAD

**Issue by aytunch** [lejard-h/google_maps_webservice#41]
I found out that google's place picker is deprecated as written here:
[Place Picker](https://developers.google.com/places/android-sdk/placepicker)

Does this plugin have anything to do with it? Sorry if they are not related. Just had to make sure before using this awesome plugin:)

**Comment by lejard-h** [comment]
Not related to this package that use the web service api https://developers.google.com/maps/apis-by-platform#web_service_apis
