### ISSUE TITLE
PlaceDetails.fromJson - check for missing response field

### ISSUE THREAD

**Issue by pratikpparikh** [lejard-h/google_maps_webservice#43]
Defect,  google api allows you to get place details with selective field as they charge based on the information you access.  The fromJson method should do appropriate check for null and empty before assigning the value to object.

**Comment by SebastianEngel** [comment]
I also just run into 
```
NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map(Closure: (dynamic) => AddressComponent
```
when I was trying to fetch PlacesDetails with fields set to "formatted_address" only. In this case "address_components" is not in the response and .map() is called on null. 
The problematic line is in [places.dart](https://github.com/lejard-h/google_maps_webservice/blob/884165f091bc7271e376f9ee6bc7df509f42abaf/lib/src/places.dart#L567)
