### ISSUE TITLE
Obtain image automaticaly

### ISSUE THREAD

**Issue by KyllianDM** [lejard-h/google_maps_webservice#45]
Hello,
When we do a getDetailsByPlaceId, it would be usefull to have a parameter named "photos" to tell the plugin that we want to load some photos of the spot without using the buildPhotoUrl, so have a Image variable in the Photo class.

It would be also usefull to have a getNextPicture to load the next picture.

**Comment by lejard-h** [comment]
This is not something I am planning to do. I wan't the library to match the web service behavior and keep the data models the same.
