### ISSUE TITLE
alternatives flag not correctly passed on in the directions(...) API

### ISSUE THREAD

**Issue by TomKrauss** [lejard-h/google_maps_webservice#54]
The `alternatives` flag directs the google maps API to provide alternative routes. Although a corresponding parameter exists in the APIs

- directionsWithAddress
- directionsWithLocation
- directions

this parametr is never used by the named methods and not passed on to the buildUrl(...) method, so one will always get a single route result.

**Comment by lejard-h** [comment]
This should be fix in `0.0.16`.

**Comment by TomKrauss** [comment]
cool - thank you!
