### ISSUE TITLE
Using a proxy server for API keys ?

### ISSUE THREAD

**Issue by joeblew99** [lejard-h/google_maps_webservice#56]
It's a smart idea but how do you protect access to the proxy ?
Maybe you embed the password to you proxy server ?

**Comment by lejard-h** [comment]
@sdolski Do you have an implementation example of using a proxy server ?

**Comment by sdolski** [comment]
I do not have an implementation example for you.

We are using a proxy server to enrich the request with the api key. In our case this is AWS API Gateway. To access the url you need to authenticate.

With this setup we ensure that no password and no api key is stored in the app.

Hope that helps.

**Comment by tapizquent** [comment]
Is there any example in the code that shows how to use the proxy?

**Comment by lejard-h** [comment]
Closing this, since it's not really related to the library but mostly how to setup a web proxy
