### ISSUE TITLE
type '_InternalLinkedHashMap' is not a subtype of type 'Map'

### ISSUE THREAD

**Issue by AAllport** [lejard-h/google_maps_webservice#75]
I believe the changes in b29673b are causing the following error:
> type '_InternalLinkedHashMap' is not a subtype of type 'Map'

Code Sample:
```dart
location.geometry.toJson()
```

Looks like the issue is here:
https://github.com/lejard-h/google_maps_webservice/blob/970d4b669912c290a969d7373cde1ba0e86574b1/lib/src/core.dart#L16-L21

Looks like the following is causing `map` to be inferred as an `_internalLinkedHashMap<dynamic,dynamic>` as opposed to an `_internalLinkedHashMap<String,dynamic>`
```dart
var map = {};
```

I believe the following _should_ fix it:
```dart
Map<String, dynamic> toJson() => {
    'lat': lat.
    'lng': lng,
}
```

**Comment by Skquark** [comment]
I also ran into this problem with parsing AddressComponents, and found the easy enough fix myself once I figured out what was going on.  In core.dart, everywhere you're doing `var map = {};` which casts it <dynamic, dynamic> needs to be changed to `var map = Map<String, dynamic>();` and the error's gone.  Would also work if it was explicit like `Map<String, dynamic> map = {};`  Woulda thought Dart could automatically cast to the returned type, but guess not.  I would submit this as a PR if you want, but it's a simple fix.

**Comment by AAllport** [comment]
> Your call

I mean... I'm not the author 😁

But yes, I do think I'll sub a PR.

If I do, I think I'd go down the route of expressions, Personally think they look a bit neater.
Given the data, it may be possible to narrow it down to `Map<String, float>` or something like that, although would need @lejard-h 's guidance for how they would like it!

**Comment by lejard-h** [comment]
This should be fix now with the null safety version of the package that use `json_serializale` package
