### ISSUE TITLE
App restriction

### ISSUE THREAD

**Issue by carlosgibarra82** [lejard-h/google_maps_webservice#77]
When APP Restriction is activated under google cloud platform, it stops working even with API restrictions disabled.

**Comment by zeshuaro** [comment]
This package has been updated to resolve this issue, please see https://github.com/lejard-h/google_maps_webservice/issues/85#issuecomment-752829368.

**Comment by vasilich6107** [comment]
Hi. @zeshuaro  

If I understood correctly - the restriction for android is made by SHA1 fingerprint which should be sent through the headers.
What is the approach on restriction on iOs side?

**Comment by zeshuaro** [comment]
@vasilich6107 For Android, it's using both the application ID and SHA1 fingerprint, whereas for iOS, it's using just the application ID.
