### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by DevNico** [lejard-h/google_maps_webservice#90]
Dart Null Safety is in beta and packages should start to migrate. Is a null safe pre release already in the works. If not I could offer my help migrating this package.

**Comment by lejard-h** [comment]
Yes the migration is ongoing under `nullsafety` along with migration to json_serializable

**Comment by lejard-h** [comment]
I will keep you up to date here, once the first version is ready, hopefully end of next week

**Comment by ErliSoares** [comment]
Any news about the stable version for null safety?

**Comment by pr-1** [comment]
I think this is already complete. Can you close the issue ? @DevNico

**Comment by lejard-h** [comment]
This is actually not stable yet (currently 0.0.20-nullsafety.2)

The migration is done, but I will wait for more feedback since it may break JSON deserialization (some non null field that must be nullable)

I keep this open for now

**Comment by acme-im** [comment]
@lejard-h, 0.0.20-nullsafety.5 branch throws when calling e.g.:
```
await client.getDetailsByPlaceId(
      placeId,
      fields: ["address_component"],
      sessionToken: sessionToken,
    );
```
here:
```
PlaceDetails _$PlaceDetailsFromJson(Map<String, dynamic> json) {
  return PlaceDetails(
    adrAddress: json['adr_address'] as String?,
    name: json['name'] as String,
    placeId: json['place_id'] as String,
    utcOffset: json['utc_offset'] as num?,
```
- on name and place_id, they must be declared nullable (like other fields).

Current workaround:
```
await client.getDetailsByPlaceId(
      placeId,
      fields: ["address_component", "name", "place_id"],
      sessionToken: sessionToken,
    );
```
