### ISSUE TITLE
Breaking changes in http package

### ISSUE THREAD

**Issue by Cmion** [lejard-h/google_maps_webservice#96]
<img width="1353" alt="Screenshot 2021-03-13 at 01 27 10" src="https://user-images.githubusercontent.com/40132113/111011911-44a89300-839b-11eb-9376-f07a2cc79441.png">

The code sample in my Stateful widget
```dart

 GoogleMapsPlaces places = new GoogleMapsPlaces(apiKey: AppConstants.api_key);

```

It seems to be a problem with `package:http/http.dart` expecting a `Uri` but a String is given instead.

```dart
  @protected
  Future<Response> doGet(String url, {Map<String, dynamic> headers}) {
    return httpClient.get(url, headers: headers);
  }
```

I think the correct code is supposed to be
```dart
  @protected
  Future<Response> doGet(String url, {Map<String, dynamic> headers}) {
    return httpClient.get(Uri.encodeFull(url), headers: headers);
  }
  
  @protected
  Future<Response> doPost(
    String url,
    String body, {
    Map<String, dynamic> headers,
  }) {
    final postHeaders = {
      'Content-type': 'application/json',
    };
    if (headers != null) postHeaders.addAll(headers);
    return httpClient.post(Uri.encodeFull(url), , body: body, headers: postHeaders);
  }

```

**Comment by Cmion** [comment]
I used this last week before upgrading to flutter 2.0 and it seems to be working fine.

I don't know if this is caused by the upgrade

**Comment by Cmion** [comment]
There's already a pull request that fixes this.

[https://github.com/lejard-h/google_maps_webservice/pull/95]

**Comment by lejard-h** [comment]
This should be fix if you use the null safety version of the package

**Comment by Cmion** [comment]
Ok thanks
